name: Deploy Azure Function App - Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install production dependencies
        run: |
          npm install --omit=dev

      - name: Zip backend code
        run: |
          zip -r functionapp.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-functionapp
          path: functionapp.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E619FA2E59C341D8845E5868AB5345E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B9AA729A29C349CEA0181DBCA4FCFD0E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3C072746B7094217AEBA2870CF57139D }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'maanit-func'
          package: 'functionapp.zip'
