name: Build and deploy Node.js project to Azure Function App - maanit-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          # If you have a build step, run it here
          # npm run build --if-present

      - name: Prune dev dependencies
        run: npm prune --production

      - name: Create zip deployment package
        run: |
          zip -r function-app.zip . -x "node_modules/.cache/*" "*.git*" "test/*"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: function-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: function-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_61096FC4A7884FAA8AF424F1328639B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B0B8D447AF2A472EA6EB35E768D6FBDC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C9A57F9E6B440709C1BCCF991AB60A8 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'maanit-func'
          slot-name: 'Production'
          package: './function-app.zip'
